#!/bin/bash
# Nombre: RecoverDrake -- RecoverSkype
# Parte: WebCam en Skype activa
# Versión: 2.0.0

sed -i '/Exec=skype/d' /usr/share/applications/skype.desktop
echo "Exec=sh -c 'export XLIB_SKIP_ARGB_VISUALS=1 && LD_PRELOAD=/usr/lib/libv4l/v4l1compat.so /usr/bin/skype'" >> /usr/share/applications/skype.desktop
