#!/bin/bash
# Nombre: RecoverDrake -- RecoveSop
# Parte: Matar señal de sop activa
# Versión: 1.6.0

      if [ "0" = `ps -e|grep "sp-sc"|awk {'print $4'}| wc -l` ]
        then
            RETURN="Sin procesos sop que matar"
        else
            kill -9 `ps -ef|grep -v grep |grep sp-sc| awk '{print $2}'`
            RETURN="Procesos sop matados"
        fi

echo $RETURN\_`date`
