#!/bin/bash
# Porque no instalar los mismos paquetes que se tenian antes de una actualización
# Este script hace eso y más
# Autor: Juan Jose Mauriz Pardo (kapyderi en blogdrake)
# Contribuciones: Drakor, Katnatek, Motitos, Will
# Parte del codigo basado en Tuningdrake para la configuración de los repositorios
# Nombre: RecoverDrake
# Versión: 0.5.0

ScriptVersion="0.5.0"
user1="`who|awk 'NR>2 {print $1}'|cut -d ' ' -f 2`"
export IFS=" "
if [ -z "`which	zenity`" ]; then
  echo "Necesita zenity para ejecutar RecoverDrake"
  urpmi zenity
  exit 1;
fi
if [ "`whoami`" = "root" ]; then
 if [ "$#" = 1 ]; then
  if [ "$1" != "--auto" -a "$1" != "--auto-mib" ]; then
   zenity --warning --text="Ejecute RecoverDrake sin parametros para un modo
   interactivo o con los siguientes parametros:

   --auto para un funcionamiento automatico sin configurar los repositorios MIB
   --auto-mib para un funcionamiento automatico configurando los repositorios MIB"
   exit 1;
  fi;
 fi
 if [ "$#" = 0 ]; then
  zenity --question --title="RecoverDrake by Kapyderi" --text="
  Kapyderi 2010

  RecoverDrake $ScriptVersion [Licencia: GPL 2 ó superior]

  Este script pretende facilitar una instalación limpia. 
  Recopila todos los paquetes instalados en su equipo, 
  antes de la instalación y luego los vuelca para dejarlo
  todo como estaba anteriormente.

  Tambien sirve para copiar los .rpms de un equipo a otro.

  Utilizelo bajo su responsabilidad, ya que no hay ninguna 
  garantia por el creador. El responsable es el que lo usa.

  Es aconsejable, tener tu /home en una partición aparte, 
  ya que con tu home y con RecoverDrake, no te habras 
  dado cuenta de que has actualizado el sistema.
 
  Las opciones se basan en preferencias personales  para no 
  tener que estar recordando las instalaciones de una 
  distribución (versión) a otra.

  A groso modo es todo el proceso que realiza nuestra 
  herrramienta RecoverDrake. Espero que la disfruten, como 
  yo realizandola. Gracias por usarla.

  ¿Desea Continuar?" --ok-label="Continuar" --cancel-label="Leer mas (recomendable para su uso)";
  if [ "$?" = 1 ]; then
   zenity --text-info --width="600" --height="400" --title="Acerca de..." --filename=/root/acercade.txt
  fi
 fi
 echo "Creando configuración de usuario..."
 user=`zenity --entry \
 --title="Nombre del usuario" \
 --text="Introduzca el nombre del usuario donde se realizarán todos los procesos" \
 --entry-text="$user1"`
 if [ $user = `grep $user /etc/passwd | cut -d ":" -f 1` ]; then
  zenity --info --text="
  El usuario donde se generarán los ficheros es...

  $user

  La ruta por defecto será... /home/$user/Documentos.
 
  NOTA: Puedes seleccionar, si lo deseas, una ruta
  alternativa."
 else
  zenity --info --text="
  El usuario $user no existe en su sistema.

  Compruebe que ha introducido el nombre
  de usuario correcto.

  Para evitar problemas en el equipo tras esta
  ventana se cerrada RecoverDrake, por lo que 
  tendrá que volver a ejecutarlo."
  exit 1
 fi
 if [ "$?" = 0 ]; then
    List="`zenity --list --title="Lista de opciones" --text="Seleccione la(s) opcion(es) de trabajo. Desmarcadas por defecto, excepto Salvaguarda." \
    --checklist --width="400" --height="400"\
    --column="" --column="Lista de opciones" FALSE "Eliminar_repositorios" FALSE "Añadir_repositorios" FALSE "Editar_repositorios" FALSE "Actualizar_sistema" FALSE\
    "Eliminar_paquetes_huerfanos_(No_recomentado)" TRUE "Salvaguardar/Recuperar_RPM" FALSE "Probar_KDE_Inestable" FALSE "Respaldar/Recuperar_Copia_de_seguridad" FALSE\
    "Guardar/Recuperar_ficheros_de_configuración" FALSE "Instalar_Escritorios" FALSE "Solución_a_problemas_conocidos" --separator=" "`";
   else
    List="Eliminar_repositorios";
   fi
   echo Se procede a su solicitud...
   for i in $List ; do
   case $i in
    "Eliminar_repositorios")
    zenity --question --title="Quitar repositorios" --text="

    ELIMINAR CONFIGURACION DE REPOSITORIOS
    
    IMPORTANTE: Esta opción solo es valida, si los repositorios 
    suelen fallar, ya que los elimina y los vuelve a crear con
    una nueva configuración.

    Proceda con cuidado!!!    

    ¿Desea quitar repositorios?" --ok-label="Eliminar repositorios" --cancel-label="Continuar sin eliminar";
    if [ "$?" = 0 ]; then 
     echo "Quitando repositorios..."
     (
     echo "10" ; sleep 1
     echo "# Eliminando repositorios..."; sleep 1
     echo "20"; sleep 1
     echo "Esta linea sera ignorada"; sleep 1
     echo "50" ; sleep 1
     echo "Esta linea sera ignorada"; sleep 1 
     echo "75"; sleep 1
     echo "# Repositorios eliminados satisfactoriamente"; sleep 1
     echo "100"; sleep 1 
     ) |
     zenity --progress \
     --title="Comprobación de repositorios" \
     --text="Eliminando repositorios..." \
     --auto-close \
     --percentage=0
     if [ "$?" = -1 ] ; then
      zenity --error \
      --text="Elimminación cancelada."
     fi
     echo Realizando proceso...
     urpmi.removemedia -a
    fi;;
    "Añadir_repositorios")
    zenity --question --title="Volver a configurar repositorios" --text="

    AÑADIR REPOSITORIOS

    Se llamará a los servidores y se volveran a configurar
    los repositorios o marcando solo la opción Otros, se 
    configurará un repositorio manualmente.

    ¿Desea configurar repositorios?" --ok-label="Configurar repositorios" --cancel-label="Continuar sin configurar";
    if [ "$?" = 0 ]; then 
     echo "Configurando y añadiendo repositorios..."
     (
     echo "10" ; sleep 1
     echo "# Rastreando repositorios..."; sleep 1
     echo "20"; sleep 1
     echo "Esta linea sera ignorada"; sleep 1
     echo "50"; sleep 1
     echo "# Se procede a su instalación...sea paciente"; sleep 1 
     echo "75"; sleep 1
     echo "Esta linea sera ignorada"; sleep 1
     echo "100" 
     ) |
     zenity --progress \
     --title="Comprobación de repositorios" \
     --text="Rastreando los repositorios..." \
     --auto-close \
     --percentage=0
     if [ "$?" = -1 ] ; then
      zenity --error \
      --text="Comprobanción cancelada."
     fi
     urpmq --list-media > /tmp/lista
     export Media="`cat /tmp/lista`"
     export NumMediaAct="`cat /tmp/lista|wc -l`"
     export NumMediaOld="$NumMediaAct"
     export Arch="`uname -m`"
     export Arch2="32"
     export Version="`cat /etc/release|cut -d ' ' -f 4`"
     export DistArch="`cat /etc/release|cut -d ' ' -f 7`"
     export Devel="`grep -i cooker /etc/release`"
     rm -f /tmp/lista
     rm -f /var/cache/urpmi/mirrors.cache
     #Elección de repositorios
     if [ "$#" = 0 ]; then
      List2="`zenity --list --title="Listado de Repositorios" --text="Seleccione su(s) repositorio(s). Marcados por defecto." \
      --checklist --width="400" --height="290"\
      --column="" --column="Listado de repositorios" TRUE "Oficiales" TRUE "PLF" TRUE "MIB" TRUE\
      "BDK" TRUE "MUD" FALSE "Otro" --separator=" "`";
     else
      List2="Oficiales";
     fi
     echo Sea paciente, este proceso, suele ser prolongado...
     for i in $List2 ; do
     case $i in
      "Oficiales")
      #Configuración de Repositorios Oficiales
      if [ "$NumMediaAct" -le "2" ]; then
       if [ -z "$Devel" ]; then
        urpmi.addmedia --wget --distrib --mirrorlist \
        "http://api.mandriva.com/mirrors/basic.$Version.$DistArch.list"
        NumMediaOld="$NumMediaAct"
        NumMediaAct="`urpmq --list-media|wc -l`"
        if [ "$NumMediaAct" = "$NumMediaOld" ]; then
        #Configurando ftp://distrib-coffee.ipsl.jussieu.fr en caso de no poder configurar los
        #Repositorios desde la lista de servidores
        urpmi.addmedia --wget --distrib \
        "ftp://distrib-coffee.ipsl.jussieu.fr/pub/linux/MandrivaLinux/official/$Version/$DistArch" ;
       fi;
      else
       urpmi.addmedia --wget --distrib --mirrorlist \
       "http://api.mandriva.com/mirrors/basic.cooker.$DistArch.list"
       NumMediaOld="$NumMediaAct"
       NumMediaAct="`urpmq --list-media|wc -l`"
       if [ "$NumMediaAct" = "$NumMediaOld" ]; then
        #Configurando ftp://distrib-coffee.ipsl.jussieu.fr en caso de no poder configurar los
        #Repositorios desde la lista de servidores
        urpmi.addmedia --wget --distrib \
        "ftp://distrib-coffee.ipsl.jussieu.fr/pub/linux/MandrivaLinux/devel/cooker/$DistArch" ;
       fi;
      fi
      NumMediaAct="`urpmq --list-media|wc -l`"
      if [ "$NumMediaAct" = "$NumMediaOld" ]; then 
       return 1;
      fi
     fi
     if [ "$?" = 1 ]; then 
      zenity --warning --text="Fallo al intentar configurar los repositorios Oficiales
      RecoverDrake no puede continuar, verifique la configuración de la red y vuelva\
      a ejecutar RecoverDrake"
      exit 1;
     else
      export NumMediaOld="$NumMediaAct";
     fi;;
     "PLF")
     #Configuración de Repositorios PLF
     if [ -z "`echo $Media|grep -i "plf"`" ]; then
      if [ -z "$Devel" ]; then
       urpmi.addmedia --wget --distrib --mirrorlist \
       "http://plf.zarb.org/mirrors/$Version.$DistArch.list"
       NumMediaOld="$NumMediaAct"
       NumMediaAct="`urpmq --list-media|wc -l`"
       if [ "$NumMediaAct" = "$NumMediaOld" ]; then
        #Configurando ftp://distrib-coffee.ipsl.jussieu.fr en caso de no poder configurar los
        #Repositorios desde la lista de medios
        urpmi.addmedia --wget --distrib \
        "ftp://distrib-coffee.ipsl.jussieu.fr/pub/linux/plf/mandriva/cfg/$Version/$DistArch" ;
       fi
      else
       urpmi.addmedia --wget --distrib --mirrorlist \
       "http://plf.zarb.org/mirrors/cooker.$DistArch.list"
       NumMediaOld="$NumMediaAct"
       NumMediaAct="`urpmq --list-media|wc -l`"
       if [ "$NumMediaAct" = "$NumMediaOld" ]; then
        #Configurando ftp://distrib-coffee.ipsl.jussieu.fr en caso de no poder configurar los
        #Repositorios desde la lista de medios
        urpmi.addmedia --wget --distrib \
        "ftp://distrib-coffee.ipsl.jussieu.fr/pub/linux/plf/mandriva/cfg/cooker/$DistArch" ;
       fi
      fi
      NumMediaAct="`urpmq --list-media|wc -l`"
      if [ "$NumMediaAct" = "$NumMediaOld" ]; then
       return 1;
      fi
     fi
     if [ "$?" = 1 ]; then
      zenity --warning --text="Fallo al intentar configurar los repositorios PLF
      RecoverDrake no puede continuar, verifique la configuración de la red y vuelva\
      a ejecutar RecoverDrake"
      exit 1;
     else
      export NumMediaOld="$NumMediaAct";
     fi;;
     "MIB")
     #Configuración de Repositorios MIB
     if [ -z "`echo $Media|grep -i "mib"`" -a -z "$Devel" ]; then
      if [ "$#" = 0 ]; then
       zenity --question --title="Repositorios adicionales" \
       --text="Configurar los repositorios MIB le proporciona acceso a 
       versiones más recientes de algunas aplicaciones
 
       ¿Desea configurar los repositorios MIB?
       (Si duda responda No)" --ok-label="Configurar" --cancel-label="No configurar"
       Configurar="$?";
      else
       case "$1" in
        "--auto")Configurar=1;;
        "--auto-mib")Configurar=0;;
       esac;
      fi
      if [ "$Configurar" = "0" ]; then
       if [ -z "`echo $Media|grep -i "mib"`" -a -z "$Devel" ]; then
        urpmi.addmedia --wget --update MIB-basic_${Arch2} http://mib.pianetalinux.org/MIB/$Version/${Arch2}/basic/ with media_info/synthesis.hdlist.cz &&
        urpmi.addmedia --wget MIB-experts_${Arch2} http://mib.pianetalinux.org/MIB/$Version/${Arch2}/experts/ with media_info/synthesis.hdlist.cz
        if [ "$?" != "0" ]; then
         exit 1; 
        fi;
       fi   
       if [ "$?" != "0" -a "$#" = "0" ]; then
        zenity --question --title="Error configurando Repositorios"\
        --text="Fallo al intentar configurar los repositorios MIB
        Si lo desea puede continuar con RecoverDrake o salir y volverlo a ejecutar para volver a intentar añadir estos repositorios.

        ¿Desea Continuar?" --ok-label="Continuar" --cancel-label="Salir";
        if [ "$?" = 1 ]; then exit 1; fi;
       fi
      fi
     fi;;
     "BDK")
     #Configuración de los repositorios Blogdrake
     test -z "`echo $Media|grep -i "bdk"`" && expr "$Version" ">=" "2009.1"
     if [ $? = 0  ]; then
      if [ "$#" = 0 ]; then
       zenity --question --title="Repositorios adicionales II" \
       --text="Configurar los repositorios de Blogdrake le proporciona acceso a 
       algunos paquetes que posiblemente no se encuentren en otros repositorios

       ¿Desea configurar los repositorios de Blogdrake?
       (Si duda responda No)" --ok-label="Configurar" --cancel-label="No configurar"
       Configurar="$?";
      else
       Configurar=0;
      fi
      if [ "$Configurar" = "0" ]; then
       urpmi.addmedia --update --wget Bdk-${DistArch}-free ftp://ftp.blogdrake.net/mandriva/$Version/free/${DistArch} with media_info/synthesis.hdlist.cz 
       urpmi.addmedia --update --wget Bdk-noarch-free ftp://ftp.blogdrake.net/mandriva/$Version/free/noarch with media_info/synthesis.hdlist.cz 
       urpmi.addmedia --update --wget Bdk-noarch-nonfree ftp://ftp.blogdrake.net/mandriva/$Version/non-free/noarch with media_info/synthesis.hdlist.cz 
       urpmi.addmedia --update --wget Bdk-${DistArch}-nonfree ftp://ftp.blogdrake.net/mandriva/$Version/non-free/${DistArch} with media_info/synthesis.hdlist.cz 
       if [ "$?" != "0" ]; then
        return 1;
       fi
       if [ "$?" != "0" -a "$#" = "0" ]; then
        zenity --question --title="Error configurando Repositorios"\
        --text="Fallo al intentar configurar los repositorios Blogdrake
        Si lo desea puede continuar con RecoverDrake o salir y volverlo a ejecutar para volver a intentar añadir estos repositorios.

        ¿Desea Continuar?" --ok-label="Continuar" --cancel-label="Salir";
        if [ "$?" = 1 ]; then exit 1; fi;
       fi
      fi
     fi;;
     "MUD")
     #Configuración de los repositorios de MUD
     test -z "`echo $Media|grep -i "mud"`" && expr $Version \>= 2007.1
     if [ $? = 0 ] ; then
      if [ "$#" = 0 ]; then
       zenity --question --title="Repositorios adicionales III" \
       --text="Configurar los repositorios de MUD le proporciona acceso a 
       algunos paquetes que posiblemente no se encuentren en otros repositorios

       ¿Desea configurar los repositorios de MUD?
       (Si duda responda No)" --ok-label="Configurar" --cancel-label="No configurar"
       Configurar="$?";
      else
       Configurar=0;
      fi
      if [ "$Configurar" = "0" ]; then
       if [ -z "`echo $Media|grep -i "mud"`"  ]; then
        expr $Version \>= 2007.1 && 
        urpmi.addmedia --wget MUD-${DistArch} ftp://ftp.mandrivauser.de/rpm/GPL/$Version/$DistArch/release/ \
        with media_info/synthesis.hdlist.cz
        if [ "$?" != "0" ]; then
         return 1; 
        fi
       fi
       if [ "$?" != "0" -a "$#" = "0" ]; then
        zenity --question --title="Error configurando Repositorios"\
        --text="Fallo al intentar configurar los repositorios MUD
        Si lo desea puede continuar con RecoverDrake o salir y volverlo a ejecutar para volver a intentar añadir estos repositorios.

        ¿Desea Continuar?" --ok-label="Continuar" --cancel-label="Salir";
        if [ "$?" = 1 ]; then exit 1; fi;
       fi 
      fi
     fi;;
     "Otro")
     #Configuración de los repositorios a mano
     Repo=`zenity --entry \
     --title="Nombre del repositorio" \
     --text="Introduzca el nombre del repositorio completo:" \
     --entry-text="Repositorio manual"`
     $Repo
    esac;
    done;
   fi;;
   "Editar_repositorios")
   zenity --question --title="Editar repositorios" --text="

   EDITAR/CONFIGURAR REPOSITORIOS
    
   Con esta opción Vd.puede EDITAR, HABILITAR, 
   DESHABILITAR e incluso BORRAR cualquier 
   repositorio que haya en su sistema.
   Muy util cuando un repositorio le da problemas.

   Proceda con cuidado!!! Habilitar repositorios debugs
   o Testing,puede desestabilizar su sistema.    

   ¿Desea editar repositorios?" --ok-label="Editar repositorios" --cancel-label="Continuar sin editar";
   if [ "$?" = 0 ]; then 
    echo Entrando en edición de repositorios en modo gráfico...
    drakrpm-edit-media
   fi;;
   "Actualizar_sistema")
   zenity --question --title="Actualizar el sistema"\
   --text="

   ACTUALIZACION DE PAQUETES

   IMPORTANTE: Esta actualización se hace automatica,
   por lo que Vd. no podrá seleccionar los paquetes
   a instalar.
 
   (si tiene dudas, pinche en la botón no)
   
   ¿Desea actualizar su sistema ahora?" --ok-label="Si, actualizar"\
   --cancel-label="Ahora No"
   if [ "$?" = "0" ]; then
    echo "Actualizando sistema, sea paciente..."
    (
    echo "10"; sleep 1
    echo "#Procesando..."; sleep 1
    echo "50"; sleep 1 
    echo "#Instalando actualizaciones"; sleep 1 
    echo "100"
    ) | 
    zenity --progress --title="Comprobación de repositorios" --text="Actualizando sistema...espere por favor" --auto-close  --auto-kill --percentage=0
    if [ "$?" = -1 ] ; then
     zenity --error \
     --text="Elimminación cancelada."
    fi
    echo Sea paciente, este proceso, suele ser prolongado...
    urpmi --wget --auto --force --auto-update
   fi;;
   "Eliminar_paquetes_huerfanos_(No_recomentado)")  
   zenity --question --title="Comprobar paquetes huerfanos"\
   --text="
    
   ELIMINAR PAQUETES HUERFANOS

   PRECACION: Proceda con sumo cuidado, ya que esta
   opción puede desestabilizar su sistema.

   Es importante que entienda lo que esta haciendo con 
   esta opción.

   (si tiene dudas pinche en el botón no)

   Se ha incluido un codigo para que se generé un 
   fichero de lo eliminado y asi poder recuperarlo si
   tenemos la necesidad y esta ubicado en 
   /home/$user/Documentos/BackOrphans.lst
    
   ¿Desea rastrear y eliminar los paquetes huerfanos?" --ok-label="Si, Comprobar"\
   --cancel-label="Ahora No"
   if [ "$?" = "0" ]; then
    echo "Buscando paquetes huerfanos..."
    (
    echo "10"; sleep 1
    echo "#Procesando..."; sleep 1
    echo "50"; sleep 1 
    echo "#Procesando datos..."; sleep 1
    echo "100"
    ) | 
    zenity --progress --title="Comprobación de repositorios" --text="Actualizando sistema...espera por favor" --auto-close  --auto-kill --percentage=0
    if [ "$?" = -1 ] ; then
     zenity --error \
     --text="Elimminación cancelada."
    fi
    echo Realizando proceso...
    urpme --auto-orphans >> /home/$user/Documentos/BackOrphans.lst
   fi
   zenity --question --title="Recuperar paquetes huerfanos"\
   --text="

   Si no esta satisfecho con la eliminación de los 
   paquetes huerfanos, puedes recuperarlos con esta
   utilidad.

   Solo comentar que se recuperará, la ultima
   eliminación de paquetes huerfanos.

   ¿Desea recuperar paquetes huerfanos?" --ok-label="Si, recuperar"\
   --cancel-label="Ahora No"
   if [ "$?" = "0" ]; then
    for Recuperar in `cat /home/$user/Documentos/BackOrphans.lst` 
     do
      urpmi -a --auto $Recuperar 
     done 
   fi
   ;;
   "Salvaguardar/Recuperar_RPM") 
   zenity --question --title="Hacer salvaguarda de rpm's" --text="

   SALVAGUARDA DE LISTADO DE PAQUETES INSTALADOS EN 
   SU EQUIPO

   IMPORTANTE: Esta opción sirve para hacer una salvaguarda
   de sus paquetes antes de la actualización/instalación.

   Utilizelo solo para este proposito.

   Generará un fichero ubicado en su /home/$user/
   Documentos/ llamado PackAnt.lst, sino se expecifica lo
   contrario.

   En el caso de existir un fichero anterior con el mismo
   nombre será eliminado y generado de nuevo.

   Es importante que lo guarde en un sitio seguro, ya que se 
   necesitará para la actualización posterior o por 
   inestabilidad del sistema.
 
   Si tiene su /home en una partición aparte, no debe tener
   ningún problema, ya que siempre tendrá localizado dicho
   fichero, sino es asi, deberá ser grabado en un Pendrive
   para futuras actualizaciones o volcados. 
 
   ¿Crear fichero?" --ok-label="Si" --cancel-label="No";
   if [ "$?" = 0 ]; then 
    echo "Realizando salvaguarda..."
    (
    echo "10" ; sleep 1
    echo "# Actualizando los rpm's del sistema"
    FILE=`zenity --save --filename=/home/$user/Documentos/PackAnt.lst --file-selection --title="Seleccione donde guardar el fichero de salvaguarda"`

        case $? in
                 0)
                        echo "\"$FILE\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";;
                -1)
                        echo "No ha seleccionado ningún archivo.";;
        esac
    echo "20" 
    echo "# Creando fichero .lst"
    (rpm -qa --queryformat='%{N} ' >> $FILE)  
    echo "50" 
    echo "Esta linea sera ignorada" 
    echo "75" 
    echo "# Fichero creado correctamente en la ruta /home/$user/Documentos/PackAnt.lst"
    echo "100" 
    ) |
    zenity --progress \
    --title="Salvando rpm's del sistema Mandriva" \
    --text="Rastreando los rpm's instalados..." \
    --percentage=0
    if [ "$?" = -1 ] ; then
     zenity --error \
     --text="Actualización cancelada."
    fi
   else
    zenity --question --title="Actualizar rpm's" --text="

    RECUPERAR LISTADO DE PAQUETES Y ACTUALIZAR EQUIPO

    IMPORTANTE: Esta opción sirve para recuperar los 
    paquetes despues de la instalación/actualización.

    Utilizelo solo para este proposito.

    IMPORTANTE: Si su /home esta en una partición aparte, 
    continue sin problemas, sino es asi, copie el fichero
    denominado PackAnt.lst en la ubicación:
    /home/$user/Documentos, sino expecifica otra ruta,
    antes de realizar este paso, ya que sino es asi, no
    podrá realizarlo.

    Instalará todos los paquetes guardados, desechando los 
    ya instalados.

    Para poder llevar un seguimiento se creará un fichero
    denominado RegRecoverxxxxxx.lst con los procesos
    realizados durante el volcado en la ubicación:
    /home/$user/Doocumentos

    Este proceso, puede tardar un tiempo, sea paciente, 
    la espera lo merece. 
 
    ¿Actualizar paquetes?" --ok-label="Si" --cancel-label="No";
    if [ "$?" = 0 ]; then 
     variable=`rpm -qa|grep -i mandriva-release|grep -v common|cut -f3 -d '-'`
     echo Estas utilizando la versión de Mandria $variable
     if [ $variable="free" ]; then  
      sed 's/one-/free-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/One-/Free-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-one/-free/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-One/-Free/g' -i /home/kapyderi/Documentos/PackAnt.lst
      sed 's/flash-/free-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/Flash-/Free-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-flash/-free/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-Flash/-Free/g' -i /home/kapyderi/Documentos/PackAnt.lst
      sed 's/powerpack-/free-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/Powerpack-/Free-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-powerpack/-free/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-Powerpack/-Free/g' -i /home/kapyderi/Documentos/PackAnt.lst
     fi;
     if [ $variable="one" ]; then
      sed 's/free-/one-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/Free-/One-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-free/-one/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-Free/-One/g' -i /home/kapyderi/Documentos/PackAnt.lst
      sed 's/flash-/one-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/Flash-/One-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-flash/-one/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-Flash/-One/g' -i /home/kapyderi/Documentos/PackAnt.lst
      sed 's/powerpack-/one-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/Powerpack-/One-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-powerpack/-one/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-Powerpack/-One/g' -i /home/kapyderi/Documentos/PackAnt.lst
     fi;
     if [ $variable="flash" ]; then
      sed 's/free-/flash-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/Free-/Flash-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-free/-flash/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-Free/-Flash/g' -i /home/kapyderi/Documentos/PackAnt.lst
      sed 's/one-/flash-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/One-/Flash-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-one/-flash/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-One/-Flash/g' -i /home/kapyderi/Documentos/PackAnt.lst
      sed 's/powerpack-/flash-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/Powerpack-/Flash-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-powerpack/-flash/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-Powerpack/-Flash/g' -i /home/kapyderi/Documentos/PackAnt.lst
     fi;
     if [ $variable="powerpack" ]; then
      sed 's/free-/powerpack-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/Free-/Powerpack-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-free/-powerpack/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-Free/-Powerpack/g' -i /home/kapyderi/Documentos/PackAnt.lst
      sed 's/one-/powerpack-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/One-/Powerpack-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-one/-powerpack/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-One/-Powerpack/g' -i /home/kapyderi/Documentos/PackAnt.lst
      sed 's/flash-/powerpack-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/Flash-/Powerpack-/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-flash/-powerpack/g' -i /home/kapyderi/Documentos/PackAnt.lst & sed 's/-Flash/-Powerpack/g' -i /home/kapyderi/Documentos/PackAnt.lst
     fi;   
     fecha=`date +%d%m%y`
     echo "Realizando volcado..."
     echo Registrando datos en el fichero RegRecover$fecha.lst.
     echo Durante este proceso, solo podrá ver el acceso a los paquetes via Internet. Para poder hacer un seguimiento de lo que se esta procesando, tendrá que acceder al fichero de la ruta /home/$user/Documentos/RegRecover.lst
     echo Sea paciente, este proceso, suele ser prolongado, según paquetes a actualizar...
     FILE=`zenity --filename=/home/$user/Documentos/PackAnt.lst --file-selection --title="Seleccione el fichero de volcado de rpm's"`

        case $? in
                 0)
                        echo "\"$FILE\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";;
                -1)
                        echo "No ha seleccionado ningún archivo.";;
        esac
     for volcado in `cat $FILE`
       do
         urpmi -a --auto $volcado >> /home/$user/Documentos/RegRecover$fecha.lst 
       done
    zenity --question --title="Visualizar Registro de acciones de volcado" --text="

    VISUALIZAR REGISTRO DE VOLCADO

    Si quiere puede ver el registro grabado con las 
    acciones realizadas por RecoverDrake, en el 
    archivo RegRecover$fecha.

    ¿Visualizar ahora?" --ok-label="Si, quiero verlo" --cancel-label="No, no es necesario";
     if [ "$?" = 0 ]; then
      kwrite /home/$user/Documentos/RegRecover$fecha.lst
     fi; 
    fi;
   fi;;
   "Probar_KDE_Inestable")
   if [ "$#" = 0 ]; then
     List4="`zenity --list --title="Probar versiones inestables de Kde" --text="Seleccione la opción que quiera." \
     --checklist --width="400" --height="290"\
     --column="" --column="Menu de prueba de nuevas versiones de KDE" TRUE "Añadir_kde_inestable" TRUE "Actualizar_kde_inestable" FALSE "Desinstalar_kde_inestable" --separator=" "`";
   else
     List4="Añadir_kde_inestable";
   fi
    for i in $List4 ; do
     case $i in
      "Añadir_kde_inestable")     
      echo Recogiendo datos de configuración...
      nombre=`zenity --entry \
      --title="Nombre del repositorio" \
      --text="Introduzca el nombre con el que quieras que aparezca el repositorio:" \
      --entry-text="KDE4"`
      ftp=`zenity --entry \
      --title="Dirección de ubicación del repositorio" \
      --text="Introduzca el dirección de internet del repositorio:" \
      --entry-text="Dirección ftp/html sin media_info/systhesis.hdlist.cz"`
      echo actualizando repositorio...
      urpmi.addmedia $nombre $ftp with media_info/synthesis.hdlist.cz
      if [ "$nombre"=`urpmq --list-media | grep $nombre` ]; then
       echo creando respaldo para restauración de kde..
       FILE1=`zenity --save --filename=/home/$user/Documentos/BackupKde.lst --file-selection --title="Seleccione el fichero de volcado de paquetes kde"`
       case $? in
                 0)
                        echo "\"$FILE1\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";;
                -1)
                        echo "No ha seleccionado ningún archivo.";;
       esac
       urpmq --list --media $nombre >> $FILE1
       echo proceso realizado con exito.
      fi;;
      "Actualizar_kde_inestable")
      echo Recogiendo datos de configuración...
      nombre=`zenity --entry \
      --title="Nombre del repositorio kde" \
      --text="Introduzca el nombre del repositorio kde:" \
      --entry-text="KDE4"`
      echo Realizando simulación para incompatibilidad...
      urpmi --auto-update --test --media $nombre
      zenity --question --title="Comprabación de compatibilidad" --text="

      Si no ha habido error de compatibilidad durante el 
      proceso de test, puede seguir con la instalación.

      IMPORTANTE: Tenga en cuenta que si continua con 
      errores el proceso puede ser perjudicial para su
      equipo y hacerlo inestable.
   
      ¿Actualizar?" --ok-label="Si" --cancel-label="No";
      if [ "$?" = 0 ]; then 
       echo Realizando instalación...
       urpmi --auto-select
       echo Actualización realizada.
      fi
      ;;
      "Desinstalar_kde_inestable")
      nombre=`zenity --entry \
      --title="Nombre del repositorio kde" \
      --text="Introduzca el nombre del repositorio kde:" \
      --entry-text="KDE4"` 
      echo Removiendo soporte $nombre...
      urpmi.removemedia $nombre
      #FILE2=`zenity --filename=/home/$user/Documentos/BackupKde.lst --file-selection --title="Seleccione el fichero de recuperación de paquetes kde"`
      #case $? in
      #          0)
      #                echo "\"$FILE2\" seleccionado.";;
      #          1)
      #                echo "No ha seleccionado ningún archivo.";;
      #         -1)
      #                echo "No ha seleccionado ningún archivo.";;
      #esac
      echo Eliminando paquetes instalados en actualización de kde...
      zenity --question --title="Verificación de eliminación/recuperación" --text="

      Ya hemos eliminado el repositorio de KDE
      inestable, por lo que nos queda desinstalar
      todos los paquetes que han sido actualizados
      para poder recuperar nuestro KDE oficial.    
  
      Continuando con el proceso de recuperacion...

      ¿Recuperar?" --ok-label="Si" --cancel-label="No";
      if [ "$?" = 0 ]; then 
       echo Realizando desinstalación de KDE...
       urpme -v --auto --force -a kde
       echo Continuando con la restauración de KDE...
       urpmi task-kde4 task-kde4-minimal 
       #for volcado2 in `cat $FILE2`
       # do
       # urpme $volcado2 && urpmi -a --auto $volcado2
       # done
      fi
      ;;
     esac;
    done;;
   "Respaldar/Recuperar_Copia_de_seguridad")
   zenity --question --title="Hacer copia de seguridad" --text="

   SALVAGUARDA DE DATOS

   Como su nombre indica, podemos hacer una copia de 
   seguridad de nuestros datos y de cualquier
   directorio..

   Generará la copia del respado en la ubicación en su 
   /home/$user/Documentos/ llamada RespaldoDrake.tar.bz2, 
   sino se expecifica lo contrario.

   En el caso de existir un fichero anterior con el mismo
   nombre será actualizado.

   Es importante que lo guarde en un sitio seguro, ya que se 
   necesitará para la actualización posterior o por 
   inestabilidad del sistema.
 
   Este proceso, puede tardar un tiempo, sea paciente, 
   la espera lo merece. 
 
   ¿Crear respaldo?" --ok-label="Si" --cancel-label="No";
   if [ "$?" = 0 ]; then 
    echo "Realizando salvaguarda..."
    Elegir=`zenity --filename=/home/$user/ --file-selection --directory --title="Seleccione que ficheros/directorios salvaguardar"`

        case $? in
                 0)
                        echo "\"$Elegir\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";;
                -1)
                        echo "No ha seleccionado ningún archivo.";;
        esac
    Salvar=`zenity --save --filename=/home/$user/Documentos/RespaldoDrake.tar.bz2 --file-selection --title="Seleccione donde guardar el fichero de salvaguarda"`

        case $? in
                 0)
                        echo "\"$Salvar\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";;
                -1)
                        echo "No ha seleccionado ningún archivo.";;
        esac
    echo Creando copia de seguridad...
    zenity --question --title="Crear nueva copia o actualizar" --text="

    Puede crear copia nueva o actualizar los datos de una ya
    creada..
    ¿Que desea hacer?" --ok-label="Crear" --cancel-label="Actualizar";
    if [ "$?" = 0 ]; then
      (tar -cjvf $Salvar $Elegir)
    else
      (tar -cjvfg $Salvar $Elegir)  
    fi
    echo dando permisos al nuevo fichero...
    chown $user $Salvar && chgrp $user $Salvar
   else
    zenity --question --title="Restaurar copia de seguridad" --text="

    RESTAURAR DATOS

    Como su nombre indica, podemos restaurar los datos 
    anteriormente salvados a su ubicación original.

    Instalará todos los datos guardados, sobreescribiendo
    los ya instalados.

    Este proceso, puede tardar un tiempo, sea paciente, 
    la espera lo merece. 
 
    ¿Restaurar copia?" --ok-label="Si" --cancel-label="No";
    if [ "$?" = 0 ]; then 
     echo "Realizando restauración de datos"
     echo Sea paciente, este proceso, suele ser prolongado, según datos a restaurar...
     Volcar=`zenity --filename=/home/$user/Documentos/RespadoDrake.tar.bz2 --file-selection --title="Seleccione el fichero de restauración"`

        case $? in
                 0)
                        echo "\"$Volcar\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";;
                -1)
                        echo "No ha seleccionado ningún archivo.";;
        esac
     tar -xjv $Volcar 
    fi;
   fi;;
   "Guardar/Recuperar_ficheros_de_configuraciónn")
   zenity --question --title="Guardar configuraciones" --text="

   GUARDAR ARCHIVOS DE CONFIGURACION

   Mediante este proceso, conseguimos salvaguardar todos los
   ficheros de configuración de nuestro equipo para poder
   recuperarlos posteriormente. 
   
   Generará la copia del respado en la ubicación en su 
   /home/$user/Documentos/ llamada ConfDrake.tar.bz2, 
   sino se expecifica lo contrario.

   En el caso de existir un fichero anterior con el mismo
   nombre será actualizado.

   Es importante que lo guarde en un sitio seguro, ya que se 
   necesitará para la actualización posterior o por 
   inestabilidad del sistema.
 
   Este proceso, puede tardar un tiempo, sea paciente, 
   la espera lo merece. 
 
   ¿Guardar configuración?" --ok-label="Si" --cancel-label="No";
   if [ "$?" = 0 ]; then 
    echo "Realizando salvaguarda de configuraciones..."
    Salvar=`zenity --save --filename=/home/$user/Documentos/ConfDrake.tar.bz2 --file-selection --title="Seleccione donde guardar el fichero de salvaguarda"`

        case $? in
                 0)
                        echo "\"$Salvar\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";;
                -1)
                        echo "No ha seleccionado ningún archivo.";;
        esac
    echo Creando copia de seguridad...
    zenity --question --title="Crear nueva copia o actualizar" --text="

    Puede crear copia nueva o actualizar los datos de una ya
    creada..
    ¿Que desea hacer?" --ok-label="Crear" --cancel-label="Actualizar";
    if [ "$?" = 0 ]; then
      (tar -cjvf $Salvar /etc)
    else
      (tar -cjvfg $Salvar /etc)  
    fi
    echo dando permisos al nuevo fichero...
    chown $user $Salvar && chgrp $user $Salvar
   else
    zenity --question --title="Restaurar copia de seguridad" --text="

    RESTAURAR ARCHIVOS DE CONFIGURACION

    Como su nombre indica, podemos restaurar los datos 
    anteriormente salvados a su ubicación original.

    Instalará todos los datos guardados, sobreescribiendo
    los ya instalados.

    Se realiza una copia de seguridad de los ficheros,
    antes de proceder al volcado.

    Dicha copia de seguridad, se encuentra ubicada en
    /home/$user/Documentos/BackupConf.tar.bz2.

    Este proceso, puede tardar un tiempo, sea paciente, 
    la espera lo merece. 
 
    ¿Restaurar configuraciones?" --ok-label="Si" --cancel-label="No";
    if [ "$?" = 0 ]; then 
     echo "Realizando restauración de configuraciones"
     echo Sea paciente, este proceso, puede ser prolongado, según datos a restaurar...
     Volcar=`zenity --filename=/home/$user/Documentos/ConfDrake.tar.bz2 --file-selection --title="Seleccione el fichero de restauración"`

        case $? in
                 0)
                        echo "\"$Volcar\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";;
                -1)
                        echo "No ha seleccionado ningún archivo.";;
        esac
     tar -xjv $Volcar 
    fi;
   fi;;
   "Instalar_Escritorios")
   if [ "$#" = 0 ]; then
     List6="`zenity --list --title="Instalador de Escritorios" --text="Seleccione el/los escritorio(s) a instalar." \
     --checklist --width="400" --height="310"\
     --column="" --column="Menu de Escritorios" FALSE "KDE" TRUE "GNOME" FALSE "E17" FALSE "Xfce" FALSE "EDE" FALSE "lxde" FALSE "Moblin" FALSE "Sugar" --separator=" "`";
   else
     List6="KDE";
   fi
    for i in $List6 ; do
     case $i in
      "KDE")     
      urpmi -a --auto task-kde4 task-kde4-minimal ;;
      "GNOME")
      urpmi -a --auto task-gnome task-gnome-minimal ;;
      "E17")
      urpmi -a --auto task-E17 task-17-minimal ;;
      "Xfce")
      urpmi -a --auto task-xfce task-xfce-minimal task-xfce-plugins ;;
      "EDE")
      urpmi -a --auto task-ede ;;
      "lxde")
      urpmi -a --auto task-lxde ;;
      "Moblin")
      urpmi -a --auto task-moblin ;;
      "Sugar")
      urpmi -a --auto task-sugar ;;
     esac;
    done;;
   "Solución_a_problemas_conocidos")
   if [ "$#" = 0 ]; then
     List3="`zenity --list --title="Solución a problemas de configuración" --text="Seleccione el/los problema(s) a resolver." \
     --checklist --width="400" --height="360"\
     --column="" --column="Problemas localizados" FALSE "Problemas_con_Wifi" FALSE "Codecs_(No_se_pueden_ver_videos_ni_oir_musica)" FALSE "Vista_previa_Dolphin_(Se_ralentizan_los_procesos)" \
     FALSE "sopcast/qsopcast_(Instalar)" FALSE "Firefox_(Sin_Adobe_Reader)" FALSE "Recuperar_contraseña_de_usuario" FALSE "VirtualBox_(No_inicia)" FALSE "RPM_database_locked" FALSE "Excluir_actualizacion_de_paquete" \
     FALSE "KTTSD_no_se_esta_ejecutando" FALSE "NTFS_sin_permisos" FALSE "Preparar_para_autocompilar"\
     FALSE "kdeinit4_(Error_al_inicio)" --separator=" "`";
   else
     List3="Problemas_con_Wifi";
   fi
    for i in $List3 ; do
     case $i in  
      "Problemas_con_Wifi")    
      if [ "$#" = 0 ]; then
       ListWifi="`zenity --list --title="Problemas con Wifi" --text="Seleccione la opción que quiera." \
       --checklist --width="400" --height="290"\
       --column="" --column="Menu de problemas con Wifi" FALSE "Wifi_intermitente_WEB/WPA" FALSE "Wifi_intermitente_abierta" --separator=" "`";
      else
       ListWifi="Wifi_intermitente_WEB/WPA";
      fi
      for i in $ListWifi ; do
       case $i in
       "Wifi_intermitente_WEB/WPA") 
       echo Configurando Wifi...
       zenity --question --title="WifiDrake by Kapyderi" --text="
       Kapyderi 2010

       WifiDrake 0.2.2 [Licencia: GPL 3 ó superior]

       Este script pretende que la wifi, cuando esta fallida, 
       y no para de desactivarse, hace que fuerze, cada minuto, 
       su ejecución de manera automatica, si esta activo.

       Este versión solo funciona con encriptaciones tipo WEB/WPA.
    
       Utilizelo bajo su criterio, ya que no hay ninguna garantia
       por el creador.

       Espero que lo disfruten, como yo realizandolo. Gracias por 
       usarlo.

       ¿Desea Continuar?" --ok-label="Continuar" --cancel-label="Salir";
       if [ "$?" = 1 ]; then exit 1; fi;
       conexion=`wc /root/wifidrake.log | cut -d ' ' -f2` 
       echo "Creando configuración de usuario..."
       user=`zenity --entry \
       --title="Nombre del usuario" \
       --text="Introduzca el nombre del usuario donde se generará el fichero .log:" \
       --entry-text="$USER"`
       zenity --info --text="
       El usuario donde se generará el fichero .log, será en...

       $user

       La ruta será /home/$user/reconecta.log"  
       if [ "$#" = 0 ]; then
        zenity --question --title="Activar wifiDrake" --text="
        Esta opción activa o desactiva WifiDrake

        ¿Activar WifiDrake?" --ok-label="Activar" --cancel-label="Desactivar";
        if [ "$?" = 1 ]; then
         echo "Borrando configuración anterior...espere por favor."
         rm -f /root/reconecta
         if [ "1" = $conexion ]; then
          crontab -l > /root/crontab_old
         else 
          crontab /root/crontab_old
         fi
        else
         echo "Borrando configuración anterior...espere por favor."
         rm -f /root/reconecta
         if [ "1" = $conexion ]; then
          crontab -l > /root/crontab_old
         else
          crontab /root/crontab_old
         fi
         echo "Creando configuración..."
         DEV=`zenity --entry \
         --title="Nombre de dispositivo" \
         --text="Introduzca el nombre de su dispotivo inalambrico (Ejemplo: wlan0):" \
         --entry-text="wlan0"` 
         ESSID=`zenity --entry \
         --title="ESSID de la red" \
         --text="Introduzca el ESSID de su dispositivo inalambrico (ejemplo: WLAN_7F):" \
         --entry-text="WLAN_7F"` 
         KEY=`zenity --entry \
         --title="CLAVE KEY de la red" \
         --text="Introduzca la CLAVE WEB de su dispositivo inalambrico (Ejemplo: Z0002CFC16C7F):" \
         --entry-text="Z0002CFC16C7F"`
         DGY=`zenity --entry \
         --title="Puera de enlace" \
         --text="Introduzca la puerta de enlace de su router (Ejemplo: 192.168.1.1):" \
         --entry-text="192.168.1.1"`
         zenity --info --text="
         Los datos introducidos son...

         Nombre de dispositivo: $DEV
         ESSID: $ESSID
         KEY: $KEY
         DGY: $DGY"
         echo "Generando fichero con su configuración..."
         echo "
         #!/bin/bash
         #
         # Script under GPL V3
         # Eduard Vidal i Tulsa  linux user 275003 (Original)
         # kapyderi (Adaptado del original con muchas mejoras para que realice ataques continuos, cada minuto y no la deje caer)
         # Tambien modifica directamente el crontab de root xD
         # kapyderi (Creador del rpm de Mandriva)
         # Versión para encriptación WEP/WPA
         # iwconfig
         DEV=$DEV                       # Dispositivo inalambrico
         ESSID="$ESSID"                 # ESSID de la red
         KEY=$KEY                       # Clave WEP/WPA
         DGY=$DGY                       # Puerta de enlace" >> /root/reconecta
         `cat /usr/sbin/datos_wifi >> /root/reconecta`
         echo "Dando permisos al fichero creado:.."
         chmod 770 /root/reconecta
         echo "Instalando linea de ajuste en el crontab de root..."
         cp /root/crontab_old /root/crontab_tmp
         echo "*/1 * * * * sudo /root/reconecta >> /home/$user/reconecta.log" >> /root/crontab_tmp
         crontab /root/crontab_tmp
         rm -f /root/crontab_tmp
         echo "Proceso realizado." >> /root/wifidrake.log
        fi
       fi;;    
       "Wifi_intermitente_abierta")
       echo Configurando Wifi...
       zenity --question --title="WifiDrake by Kapyderi" --text="
       Kapyderi 2010

       WifiDrake 0.2.2 [Licencia: GPL 3 ó superior]

       Este script pretende que la wifi, cuando esta fallida, 
       y no para de desactivarse, hace que fuerze, cada minuto, 
       su ejecución de manera automatica, si esta activo.

       Este versión solo funciona sin incriptación.
    
       Utilizelo bajo su criterio, ya que no hay ninguna garantia
       por el creador.

       Espero que lo disfruten, como yo realizandolo. Gracias por 
       usarlo.

       ¿Desea Continuar?" --ok-label="Continuar" --cancel-label="Salir";
       if [ "$?" = 1 ]; then exit 1; fi;
       conexion=`wc /root/wifidrake.log | cut -d ' ' -f2` 
       echo "Creando configuración de usuario..."
       user=`zenity --entry \
       --title="Nombre del usuario" \
       --text="Introduzca el nombre del usuario donde se generará el fichero .log:" \
       --entry-text="$USER"`
       zenity --info --text="
       El usuario donde se generará el fichero .log, será en...

       $user

       La ruta será /home/$user/reconecta.log"  
       if [ "$#" = 0 ]; then
        zenity --question --title="Activar wifiDrake" --text="
        Esta opción activa o desactiva WifiDrake

        ¿Activar WifiDrake?" --ok-label="Activar" --cancel-label="Desactivar";
        if [ "$?" = 1 ]; then
         echo "Borrando configuración anterior...espere por favor."
         rm -f /root/reconecta
         if [ "1" = $conexion ]; then
          crontab -l > /root/crontab_old
         else 
          crontab /root/crontab_old
         fi
        else
         echo "Borrando configuración anterior...espere por favor."
         rm -f /root/reconecta
         if [ "1" = $conexion ]; then
          crontab -l > /root/crontab_old
         else
          crontab /root/crontab_old
         fi
         echo "Creando configuración..."
         DEV=`zenity --entry \
         --title="Nombre de dispositivo" \
         --text="Introduzca el nombre de su dispotivo inalambrico (Ejemplo: wlan0):" \
         --entry-text="wlan0"` 
         ESSID=`zenity --entry \
         --title="ESSID de la red" \
         --text="Introduzca el ESSID de su dispositivo inalambrico (ejemplo: WLAN_7F):" \
         --entry-text="WLAN_7F"` 
         DGY=`zenity --entry \
         --title="Puera de enlace" \
         --text="Introduzca la puerta de enlace de su router (Ejemplo: 192.168.1.1):" \
         --entry-text="192.168.1.1"`
         zenity --info --text="
         Los datos introducidos son...

         Nombre de dispositivo: $DEV
         ESSID: $ESSID
         DGY: $DGY"
         echo "Generando fichero con su configuración..."
         echo "
         #!/bin/bash
         #
         # Script under GPL V3
         # Eduard Vidal i Tulsa  linux user 275003 (Original)
         # kapyderi (Adaptado del original con muchas mejoras para que realice ataques continuos, cada minuto y no la deje caer)
         # Tambien modifica directamente el crontab de root xD
         # kapyderi (Creador del rpm de Mandriva)
         # Versión sin incriptación
         # iwconfig
         DEV=$DEV                       # Dispositivo inalambrico
         ESSID="$ESSID"                 # ESSID de la red
         DGY=$DGY                       # Puerta de enlace" >> /root/reconecta
         `cat /usr/sbin/datos_wifi_open >> /root/reconecta`
         echo "Dando permisos al fichero creado:.."
         chmod 770 /root/reconecta
         echo "Instalando linea de ajuste en el crontab de root..."
         cp /root/crontab_old /root/crontab_tmp
         echo "*/1 * * * * sudo /root/reconecta >> /home/$user/reconecta.log" >> /root/crontab_tmp
         crontab /root/crontab_tmp
         rm -f /root/crontab_tmp
         echo "Proceso realizado." >> /root/wifidrake.log
        fi
       fi;;    
      esac;
     done;;
      "Codecs_(No_se_pueden_ver_videos_ni_oir_musica)")
      echo Instalando Codecs de audio y video...
      zenity --question --title="Codecs" --text="
      
      Instalación de los codecs de audio y video necesarios  
      para el buen funcionamiento multimedia, sin tener que
      instalarlos a mano.

      ¿Desea Continuar?" --ok-label="Continuar" --cancel-label="Salir";
      if [ "$?" = 1 ]; then exit 1; fi;
      CODECS="win32-codecs xanim-codecs libquicktime"
      urpmi --wget --auto real-codecs $CODECS libquicktime-x264 libquicktime-lame libquicktime-faad\
      libquicktime-faac faad2 xine-faad faac libamrnb3 libamrwb3 amrnb amrwb
      urpmi --wget --auto lame gstreamer0.10-a52dec gstreamer0.10-amrnb gstreamer0.10-amrwb\
      gstreamer0.10-faad gstreamer0.10-faac gstreamer0.10-ffmpeg mencoder gstreamer0.10-lame
      urpmi --wget --auto gstreamer0.10-flac gstreamer0.10-cdio gstreamer0.10-cdparanoia\
      ffmpeg mencoder transcode gstreamer0.10-mms ;;
      "Vista_previa_Dolphin_(Se_ralentizan_los_procesos)")
      echo Preparando matador de procesos...
      zenity --question --title="Vista previa de Dolphin" --text="
      
      Por algún motivo, al abrir Dolphin y tener videos en    
      la carpeta contenedora, puede generar que se ralentize
      el equipo, cuando ejecuta la vista previa.

      La solución es instalar este script que ira matando los
      procesos relacionados con kio_thumbnail 

      ¿Desea Continuar?" --ok-label="Continuar" --cancel-label="Salir";
      if [ "$?" = 1 ]; then exit 1; fi;
      cp /usr/sbin/matador /root/matador   
      echo "Dando permisos al fichero creado:.."
      chmod 770 /root/matador
      echo "Instalando linea de ajuste en el crontab de root..."
      cp /root/crontab_old /root/crontab_tmp
      echo "*/1 * * * * sudo /root/matador >> /home/$user/logkill.log" >> /root/crontab_tmp
      crontab /root/crontab_tmp
      rm -f /root/crontab_tmp 
      ;;
      "sopcast/qsopcast_(Instalar)")
      echo Configurando e instalando qsopcast...
      zenity --question --title="Configuración de sopcast/qsopcast" --text="
      
      IMPORTANTE: En algunos paises, utilizar este tipo de 
      software puede ser ilegal, consulte la legislación
      vigente de su pais..    
      
      sopcast y su gui qsopcast tienen la finalidad de poder 
      visionar todo tipo de televisión, deportes, peliculas
      mediante un tipo de software p2p, algunos canales
      pueden ser ilegales..

      Si tiene claro que puede utilizarlo en su pais...      

      ¿Instalar y configurar?" --ok-label="Instalar/configurar" --cancel-label="Salir";
      if [ "$?" = 1 ]; then exit 1; fi;
      echo descomprimiendo ficheros...
      tar xvzf /root/qsopcast.tar.gz 
      tar xvzf /root/sp-sc-auth.tar.gz
      echo creando directorio...
      cp /home/$user/sp-sc-auth /home/$user/.sopcast/
      echo "Instalando paquete local..."
      urpmi /home/$user/qsopcast-0.3.1.rpm
      ln -s /home/$user/.sopcast/sp-sc-auth /usr/local/bin/sopcast
      echo Borrando temporales...
      rm -f /home/$user/sp-sc-auth
      rm -f /home/$user/qsopcast-0.3.1.rpm
      echo proceso y configuración realizada.
      ;;
      "Firefox_(Sin_Adobe_Reader)")
      echo Instalando paquete Adobe Reader...
      Localizacion=AdobeReader_esp-8.1.7-1.i486.rpm
      zenity --question --title="Instalar Adobe Reader" --text="
      
      IMPORTANTE: Firefox puede dar problemas al visionar  
      formatos pdf, por lo que este apartado soluciona
      dicho problema. 

      Version actual: 

      $Localizacion  
      
      ¿Instalar?" --ok-label="Instalar" --cancel-label="Salir";
      if [ "$?" = 1 ]; then exit 1; fi;
      echo Descargando desde el servidor en modo consola...
      wget http://ardownload.adobe.com/pub/adobe/reader/unix/8.x/8.1.7/esp/$Localizacion
      echo Moviendo de ubicación...
      mv /root/$Localizacion /home/$user/$Localizacion
      echo "Instalando paquete local..."
      urpmi /home/$user/$Localizacion
      echo Borrando temporales...
      rm -f /home/$user/$Localizacion
      echo proceso realizado.
      ;;
      "Recuperar_contraseña_de_usuario")
      echo Recuperando contraseña...
      zenity --question --title="Recuperar contraseña de usuarior" --text="
      
      A veces puede ocurrir que, por algún motivo, olvidemos  
      alguna de las contraseñas de nuestro sistema, por lo 
      que con esta opción es facil de recuperar.

      La contraseña root no tiene sentido en este apartado, 
      ya que si has llegado hasta aqui, es por que la sabes,
      aunque explico como hacerlo de manera informativa:

      Lo primero a hacer es reiniciar la máquina, ya en Grub
      hay que colocarse sobre la opción de Linux y pulsar (e)
      Luego colocarse sobre la opción (kernel) y pulsar (e), 
      separa con un espacio el texto subsecuente, escribimos
      (single) y presionamos enter.
      Despues pulsa (b) para iniciar el sistema, al entrar en
      modo terminal tenemos la cuenta root, por lo que sólo
      necesitamos cambiar la contraseña con el comando:
      passwd root
      y despues reinicia el sistema para que surtan efecto los
      cambios mediante el comando (reboot)
      
      ¿Recuperar contraseña?" --ok-label="Si" --cancel-label="No";
      if [ "$?" = 1 ]; then exit 1; fi;
      Usuario=`zenity --entry \
        --title="Nombre del usuario" \
        --text="Introduzca el nombre del usuario a recuperar:" \
        --entry-text="Usuario"` 
      sudo passwd $Usuario
      echo Contraseña recuperada.
      ;;
      "VirtualBox_(No_inicia)")
      echo Configurando Virtualbox...
      zenity --question --title="Error de VirtualBox" --text="
      
      Cuando queremos ejecutar VirtualBox, es posible
      que lance un mensaje de que no se puede ejecutarlo
      y tengamos que configurarlo a la vez que prepararlo
      para proximos kernel.

      Esta función hace esa labor, creando una nueva
      configuración para su funcionamiento y por otro
      lado, haciendo que se pueda compilar con futuros
      kernels (nucleos).

      Es tan valido para versión OSE como para Oracle.
                      
      ¿Configurar VirtualBox?" --ok-label="Si" --cancel-label="No";
      if [ "$?" = 1 ]; then exit 1; fi;
      echo Buscando nucleo instalado...
      kernel=`uname -r`
      echo Su nucleo es $kernel
      kernel1=`uname -r | cut -d "-" -f2`
      echo descargando paquetes necesarios e instalando...
      urpmi dkms-virtualbox virtualbox-kernel-$kernel virtualbox-kernel-$kernel1-latest
      if [ "vboxdrv" = `find /etc/init.d/vboxdrv | cut -d "/" -f4 | cut -d " " -f1` ]; then
       echo Configurando vboxdrv
       sudo /etc/init.d/vboxdrv setup
      fi   
      echo VirtualBox configurado.
      ;;
      "RPM_database_locked")
      echo Desbloqueando urpmi...
      zenity --question --title="Base RPM bloqueada" --text="
      
      En alguna ocasión puede pasar que por alguna razón
      la base de datos de urmpi se quede bloqueada, por
      lo que es necesario desbloquearla o no se podrá 
      utilizar.

      Mediante este apartado se soluciona dicho problema.
                      
      ¿Desbloquear urpmi?" --ok-label="Si" --cancel-label="No";
      if [ "$?" = 1 ]; then exit 1; fi;
      echo Eliminando ficheros bloqueados...
      killall urpmi urpmi.update urpme rpm urpmi.addmedia
      rm -f /var/lib/urpmi/.LOCK /var/lib/rpm/RPMLOCK
      echo Base de dastos de uprmi desbloqueada.
      ;;
      "Excluir_actualizacion_de_paquete")
      if [ "$#" = 0 ]; then
       List7="`zenity --list --title="Excluir actualizacion de paquetess" --text="Seleccione la(s) accion(es) a realizar." \
       --checklist --width="400" --height="240"\
       --column="" --column="Menu de Exclusión de paquetes" TRUE "Excluir_paquete" FALSE "Vaciar_fichero_de_exclusiones" --separator=" "`";
      else
       List7="Excluir_paquete";
      fi
      for i in $List7 ; do
       case $i in
        "Excluir_paquete")     
        echo Excluyendo paquetes a actualizar...
        zenity --question --title="Paquete a excluir" --text="
      
        A veces, hay paquetes que no se actualizan de forma
        correcta o fallan las dependencias y siempre 
        aparecen para actualizar aunque no pueden ser 
        instalados, por lo que es preciso excluirlos de 
        las actualizaciones.
     
        Con esta utilidad, se puede hacer con el simple 
        hecho de introducir su nombre simple.
                            
        Ejemplo:rhymthbox

        Si por lo contrario quiere excluir un nombre y 
        todas sus variantes, debe introducirlo de la 
        siguiente manera...

        Ejemplo: /^rhymthbox/ 

        Tal cual se muestra con las barras / y el signo ^
      
        ¿Excluir paquete?" --ok-label="Si" --cancel-label="No";
        if [ "$?" = 1 ]; then exit 1; fi;
        Pack=`zenity --entry \
        --title="Nombre del paquete a excluir" \
        --text="Introduzca el nombre (simple) del paquete a excluir" \
        --entry-text=" "`      
        echo $Pack >> /etc/urpmi/skip.list
        echo Paquete introducido satisfactoriamente.
        ;;
        "Vaciar_fichero_de_exclusiones")
        echo Vaciando fichero de exclusiones...
        rm -f /etc/urpmi/skip.list
        echo "
        # Here you can specify the packages that won't be upgraded automatically
        # for example, to exclude all apache packages :
        # /^apache/" >> /etc/urpmi/skip.list
        echo Restauración del fichero de exclusiones realizado.
        ;;
       esac;
      done;;
      "KTTSD_no_se_esta_ejecutando")
      echo Configurando KTTSD y sus librerias...
      zenity --question --title="Configuración de KTTSD" --text="
      
      Por algún motivo las nuesvas versiones de kttsd y de
      jovie hacen que no funcione el lector de voces festival,
      lanzando un mensaje de que no se esta ejecutando KTTSD.

      La solución pasa por utilizar esta utilidad.

      ¿Configurar KTTSD/Jovie?" --ok-label="Si" --cancel-label="No";
      if [ "$?" = 1 ]; then exit 1; fi;
      echo Eliminando configuración anterior...
      urpme kttsd libkttsd4
      echo Descomprimiendo ficheros...
      tar xvzf /root/kttsd.tar.gz 
      echo "Instalando paquete local..."
      urpmi /home/$user/kttsd.rpm
      urpmi /home/$user/libkttsd4.rpm
      echo Excluyendo paquetes a actualizar
      if [ "kttsd" = `cat /etc/urpmi/skip.list | grep kttsd` ]; then
       echo Fichero a excluir, ya incluido en listado de exclusión.
      else       
        echo kttsd >> /etc/urpmi/skip.list
        echo libkttsd >> /etc/urpmi/skip.list
        echo Paquetes introducidos satisfactoriamente.
      fi;;
      "NTFS_sin_permisos")
      if [ "$#" = 0 ]; then
       ListNTFS="`zenity --list --title="NTFS sin permisos" --text="Seleccione el/los problema(s) a resolver." \
       --checklist --width="400" --height="290"\
       --column="" --column="Problemas de NTFS" FALSE "Permisos_para_NTFS" FALSE "Recuperar_fstab" --separator=" "`";
      else
       ListNTFS="Permisos_para_NTFS";
      fi
      for i in $ListNTFS ; do
       case $i in   
        "Permisos_para_NTFS")
        echo Dando permisos a unidades ntfs-3g...
        zenity --question --title="Configuración de NTFS" --text="
      
        Se ha apreciado un error en las unidades NTFS, en el que
        despues de escribir en ellas, aparece el mensaje:

        No se pudieron cambiar los permisos...

        no siendo problematico es bastante molesto y más si
        estas pasando varios archivos a la vez, ya que en
        cada una de los archivos aparecerá dicho mensaje.

        Se generará un fichero denominado fstab.bak con la 
        configuración anterior en la ruta /etc/fstab.bak, por lo
        que en el caso de inestabilidad, solo tendría que ser
        renombrado por /etc/fstab y volvería a su estado original.

        ¿Eliminar restricción de NTFS?" --ok-label="Si" --cancel-label="No";
        if [ "$?" = 1 ]; then exit 1; fi;
        echo Salvaguardando fstab original....
        cp /etc/fstab /etc/fstab.bak
        echo Realizando modificación de permisos...
        sed '/ntfs-3g/s/umask=000/umask=0/;/ntfs-3g/s/nouser/user/' /etc/fstab
        echo "Permisos modificados satisfactoriamente."
        zenity --info --text="Para que la nueva configuración sea efectiva, debe reiniciar el equipo."
        ;;
        "Recuperar_fstab")
        echo Recuperando fstab...
        zenity --question --title="Recuperar fstab" --text="
      
        Si has notado cualquier inestabilidad al realizar el
        proceso de Configuración de NTFS, debe utilizar esta
        opción ya que recuperará la configuración anterior
        
        Ten en cuenta que si lo haces, todos los permisos
        otorgados, se habŕan perdido.

        ¿Recuperar configuración fstab?" --ok-label="Si" --cancel-label="No";
        if [ "$?" = 1 ]; then exit 1; fi;
        echo Restaurando fichero fstab...
        mv -f /etc/fstab.bak /etc/fstab
        echo "Restauración realizada satisfactoriamente."
         zenity --info --text="Para que la nueva configuración sea efectiva, debe reiniciar el equipo."
        ;;
       esac;
      done;;
      "Preparar_para_autocompilar")
      zenity --question --title="Preparar para autocompilar" --text="
      
      A quien no le ha pasado, que al intentar compilar
      los DKMS le han dado error, por la necesidad de
      fuentes y codigo source sobre el kernel activo,
      a la vez de no tener instaladas la librerias de
      compilación gcc.

      Para poder solucionarlo, solo hay que ejecutar 
      esta utilidad y quedará resuelto.
        
      ¿Preparar kernel para autocompilado?" --ok-label="Si" --cancel-label="No";
      if [ "$?" = 1 ]; then exit 1; fi;
      echo Preparando nucleo kernel...
      kernel=`uname -r`
      echo Su kernel corresponde al nucleo $kernel
      echo Descargando paquetes necesarios...
      TipKernel=`uname -r | cut -d "-" -f2`
      VerKernel=`uname -r | cut -d "-" -f1`
      RevKernel=`uname -r | cut -d "-" -f3`
      urpmi -a --auto kernel-$TipKernel-devel-$VerKernel-$RevKernel kernel-$TipKernel-devel-latest kernel-$TipKernel-latest kernel-source-latest kernel-source-$VerKernel-$RevKernel dkms dkms-minimal gcc gcc-c++ gcc-cpp
      echo Paquetes correctamente instalados.
      zenity --info --text="Para que la nueva configuración sea efectiva, debe reiniciar el equipo."
      ;;  
      "kdeinit4_(Error_al_inicio)")
      if [ "$#" = 0 ]; then
       List4="`zenity --list --title="Errores de kde" --text="Seleccione el/los problema(s) a resolver." \
       --checklist --width="400" --height="290"\
       --column="" --column="Procesos de Kde" FALSE "Solucionar_kdeinit4" FALSE "Recuperar_configuracion" --separator=" "`";
      else
       List4="Solucionar_kdeinit4";
      fi
       for i in $List4 ; do
        case $i in  
         "Solucionar_kdeinit4")
         echo Configurando plamas de inicio...
         zenity --question --title="Error de kdeini4 al inicio de kde" --text="
       
         A veces puede ocurrir que al iniciar kde, nos 
         muestre un error de kdeinit4 y muera el
         proceso de inicio, el error es debido a una
         mala configuración de los plasmas de escritorio.   
   
         IMPORTANTE: Realizando este proceso, el escritorio
         volverá a su estado inicial, para evitar el error.
 
         Es importante que comprenda que su configuración
         personal desaparecerá y tendrá que volver a 
         configurar de nuevo su escritorio.

         Se creará una copia de seguridad de dicho fichero
         por si quisierá recuperar su configuración.
 
         Este sistema puede tambien arreglar errores de kde 
         diversos, por lo que se puede utilizar tambien para
         dicho proposito.
                  
         ¿Reconfigurar plasma?" --ok-label="Si" --cancel-label="No";
         if [ "$?" = 1 ]; then exit 1; fi;
         echo Realizando backup del fichero responsable del error...
         mkdir /home/$user/.kde4a/ && mkdir /home/$user/.kde4a/share/
         mv /home/$user/.kde4/share/config/ /home/$user/.kde4a/share/config/
         echo Borrando fichero responsable del error...
         rm -rf /home/$user/.kde4/share/config/
         echo proceso de reconiguración realizado.
         zenity --info --text="
         Si quiere recuperar su configuración solo tendrá que
         utilizar "Recuperar configuración" de este mismo
         submenu.
                 
         No olvide reiniciar sesion para que los cambios
         tengan efecto."
         ;;
         "Recuperar_configuracion")
         echo Configurando plamas de inicio...
         zenity --question --title="Recuperando configuración de Kde" --text="
       
         Mediante este proceso, vuelve a recuperar al
         estado anterior la configuración de su kde.
 
         IMPORTANTE: Si realiza este proceso, puede que
         su kde, vuelva al estado anterior a su problema,
         por lo que no habrá hecho nada.
                  
         ¿Recuperar configuración kde?" --ok-label="Si" --cancel-label="No";
         if [ "$?" = 1 ]; then exit 1; fi;
         echo Realizando recuperación de configuración...
         cp -r /home/$user/.kde4a/share/config/ /home/$user/.kde4/share/
         echo dando permisos de la nueva configuración...
         chown $user /home/$user/.kde4/share/config/ && chgrp $user /home/$user/.kde4/share/config/
         zenity --info --text="
         No olvide reiniciar sesión para que los cambios 
         tengan efecto."
         echo proceso de recuperación realizado.
         ;;
        esac;
       done;
      esac;
    done;
   esac;
  done;
 fi
echo "Proceso finalizado."
#Mensaje Final
 zenity --info --text="Felicidades $user, se han realizado con exito las tareas solicitadas."
 exit 0
else
 zenity --warning --text="RecoverDrake debe ser ejecutado por root"
 exit 1;
fi