#!/bin/bash
# Nombre: RecoverDrake -- RecoverDVD
# Parte: Arreglar fallo de apertura CD/DVD
# Versión: 1.6.0
Pack="dev.cdrom.autoclose=1"
sed -i "/$Pack/d" /etc/sysctl.conf
echo "dev cdrom.autoclose=0" >> /etc/sysctl.conf