#!/bin/bash
# Nombre: RecoverDrake -- RecoverBackup
# Parte: Hacer copia de seguridad
# Versión: 1.6.0

user=`who|awk 'NR<(NF-NR) {print $1}'|cut -d ' ' -f2`
fecha=`date +%d%m%y`

    echo "Realizando salvaguarda..."
    zenity --question --title="Que tipo de copia quiere realizar?" --text="

    Puede crear copia de un directorio o de ficheros

    ¿Que desea hacer?" --ok-label="Backup directorio" --cancel-label="Backup ficheros";
    if [ "$?" = 0 ]; then
        Elegir=`zenity --filename=/home/$user/ --file-selection --multiple --directory --title="Seleccione que directorios salvaguardar"`

        case $? in
                 0)
                        echo "\"$Elegir\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;
                -1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;
        esac
    else
	Elegir=`zenity --filename=/home/$user/ --file-selection --multiple --title="Seleccione que ficheros salvaguardar"`

        case $? in
                 0)
                        echo "\"$Elegir\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;
                -1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;
        esac
    fi
	Salvar=`zenity --save --filename=/home/$user/Documentos/RespaldoDrake$fecha.tar.gz --file-selection --title="Seleccione donde guardar el fichero de salvaguarda"`

        case $? in
                 0)
                        echo "\"$Salvar\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;                        
                -1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;                        
        esac 
    Verif=`find $Salvar`
    Elecc=`echo $Elegir | tr '|' ' '`
    Temp=`echo $Salvar | sed 's/.tar.gz/.tar/g'`
    if [ "$Salvar" = "$Verif" ]; then
	echo Actualizando archivo comprimido...	
	gzip -d $Salvar
        tar -rvf $Temp $Elecc
	gzip $Temp
    else
	echo Creando nuevo archivo comprimido...
	tar -czvf $Salvar $Elecc  
    fi
    echo dando permisos al nuevo fichero...
    chown $user $Salvar && chgrp $user $Salvar
    echo Proceso realizado con exito