#!/bin/bash
# Nombre: RecoverDrake -- RecoverConvert
# Parte: Convertir ficheros a utf8.
# Versión: 1.6.0

if [[ ! -d $1 ]]
then
        echo "¡Error en los parámetros! Uso: $0 <directorio>";
        exit 1
fi

tempfile=`tempfile 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

find $1 -type f > $tempfile;

exec 3< $tempfile

while read -u3 filename
do
        typefile=$(file --mime "$filename");
        if [[ -n $(echo $typefile | grep "text/") ]]
        then
                encoding=$(echo $typefile | cut -d'=' -f2);
                if [[ $encoding != "utf-8" ]]
                then
                        if [[ -n "$(iconv --list | grep -i $encoding)" ]]
                        then
                                tempfile2=`tempfile 2>/dev/null` || tempfile2=/tmp/test$$
                                trap "rm -f $tempfile2" 0 1 2 5 15
                                iconv --from-code=$encoding --to-code=utf-8 "$filename" > $tempfile2
                                mv -f $tempfile2 "$filename"
                                echo "$filename: $encoding -> utf8";
                        fi
                fi
        fi;
done;

exec 3<&-
