#!/bin/bash
# Nombre: RecoverDrake -- RecoverOrphans
# Parte: Eliminar paquetes huerfanos
# Versión: 1.6.0

user="`who -m|cut -d ' ' -f 2`"
   
   "Eliminar_paquetes_huerfanos_(No_recomentado)")  
   zenity --question --title="Comprobar paquetes huerfanos"\
   --text="
    
   ELIMINAR PAQUETES HUERFANOS

   PRECACION: Proceda con sumo cuidado, ya que esta
   opción puede desestabilizar su sistema.

   Es importante que entienda lo que esta haciendo con 
   esta opción.

   (si tiene dudas pinche en el botón no)

   Se ha incluido un codigo para que se generé un 
   fichero de lo eliminado y asi poder recuperarlo si
   tenemos la necesidad y esta ubicado en 
   /home/$user/Documentos/BackOrphans.lst
    
   ¿Desea rastrear y eliminar los paquetes huerfanos?" --ok-label="Si, Comprobar"\
   --cancel-label="Ahora No"
   if [ "$?" = "0" ]; then
   FILE=`zenity --save --filename=/home/$user/Documentos/BackOrphans.lst --file-selection --title="Seleccione el fichero de volcado de paquetes huerfanos"`
       case $? in
                 0)
                        echo "\"$FILE1\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";;
                -1)
                        echo "No ha seleccionado ningún archivo.";;
       esac
       
       echo "Buscando paquetes huerfanos..."
       (
       echo "10"; sleep 1
       echo "#Procesando..."; sleep 1
       echo "50"; sleep 1 
       echo "#Procesando datos..."; sleep 1
       echo "100"
       ) | 
       zenity --progress --title="Comprobación de repositorios" --text="Actualizando sistema...espera por favor" --auto-close  --auto-kill --percentage=0
    if [ "$?" = -1 ] ; then
     zenity --error \
     --text="Eliminación cancelada."
    fi
    echo Realizando proceso...
    urpme --auto-orphans >> $FILE
   fi