#!/bin/bash
# Nombre: RecoverDrake -- RecoverRename
# Parte: Quitar espacios en blanco en nombres
# Versión: 1.6.0

user=`who|awk 'NR<(NF-NR) {print $1}'|cut -d ' ' -f2`
Lugar=`pwd`
      
    echo "Realizando comprobación de nombres..."
    (
    echo "10" ; sleep 1
    FILE=`zenity --file-selection --filename=/home/$user/Documentos --directory --title="Seleccione directorio de comprobación"`

        case $? in
                 0)
                        echo "\"$FILE\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;
                -1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;
        esac
    echo "20" 
    for i in $FILE/*; do mv -v "$i" `echo $i | tr ' ' '_'`; done    
    echo "50" 
    echo "Esta linea sera ignorada" 
    echo "75" 
    echo "# Ficheros renombrados correctamente en la ruta $FILE"
    echo "100" 
    ) |
    zenity --progress \
    --title="Quitando espacios en blanco" \
    --text="Conversión en proceso..." \
    --percentage=0
    if [ "$?" = -1 ] ; then
     zenity --error \
     --text="Conversión cancelada."
    fi