#!/bin/bash
# Nombre: RecoverDrake -- RecoverSudo
# Parte: Incluir Sudo
# Versión: 1.6.0

user=`who|awk 'NR<(NF-NR) {print $1}'|cut -d ' ' -f2`

    echo "Introduciendo el usuario $user en /ect/sudoers para realizar acciones de sudo"
    echo "$user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    echo "Usuario $user introducido correctamente"