#!/bin/bash
# Nombre: RecoverDrake -- RecoverConf
# Parte: Fichero de configuración
# Versión: 1.6.0

user=`who|awk 'NR<(NF-NR) {print $1}'|cut -d ' ' -f2`
fecha=`date +%d%m%y`

    echo "Realizando salvaguarda de fichero de configuración..."
    zenity --question --title="Que tipo de copia quiere realizar?" --text="

    Puede crear copia de un directorio o de ficheros

    ¿Que desea hacer?" --ok-label="Backup directorio" --cancel-label="Backup ficheros";
    if [ "$?" = 0 ]; then
        Elegir="/etc"
    else
	Elegir=`zenity --filename=/etc --file-selection --multiple --title="Seleccione que ficheros salvaguardar"`

        case $? in
                 0)
                        echo "\"$Elegir\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;

                -1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;
        esac
    fi
	Salvar=`zenity --save --filename=/home/$user/Documentos/ConfDrake$fecha.tar.bz2 --file-selection --title="Seleccione donde guardar el fichero de salvaguarda"`

        case $? in
                 0)
                        echo "\"$Salvar\" seleccionado.";;
                 1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;                        
                -1)
                        echo "No ha seleccionado ningún archivo.";
			exit 1;;                        
        esac
    tar -cjvf $Salvar $Elegir
    echo dando permisos al nuevo fichero...
    chown $user $Salvar && chgrp $user $Salvar
    echo Proceso realizado con exito