#!/bin/bash
# Nombre: RecoverDrake -- RecoverExclu
# Parte: Excluir paquete
# Versión: 1.6.0

Pack=`zenity --entry \
        --title="Nombre del paquete a excluir" \
        --text="Introduzca el nombre del paquete a excluir

	Ejemplo: rhythmbox (Nombre simple).
	
	Ejemplo: /^rhythmbox/ (Todas las variantes)." \
        --entry-text=" "`      
        echo $Pack >> /etc/urpmi/skip.list
        echo Paquete $Pack introducido satisfactoriamente.